[package]
name = "auto-desk"
version = "0.4.1"
edition = "2021"

[[bin]]
name = "desktop-automater"
path = "src/server/main.rs"

[[bin]]
name = "auto-desk"
path = "src/client/main.rs"

[workspace]
members = [
    "workspaces/bspwm",
    "workspaces/qtile",
    "workspaces/common",
    "workspaces/wm-lib",
]

[features]
default = ["common"]
bspwm = ["dep:bspwm"]
qtile = ["dep:qtile", "dep:wm_lib"]
common = ["systemctl", "media", "dep:common"]
systemctl = []
media = []

[dependencies]
clap = "3.2.8"
shellexpand = "2.1.0"
configparser = "3.0.0"
common = { path = "workspaces/common", optional=true}
qtile = { path = "workspaces/qtile", optional=true }
bspwm = { path = "workspaces/bspwm", optional=true }
wm_lib = { path = "workspaces/wm-lib", optional=true }
tokio = {version = "1.22", features = ["net", "rt-multi-thread", "macros", "io-util"]}
