[package]
name = "auto-desk"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "desktop-automater"
path = "src/server/main.rs"

[[bin]]
name = "auto-desk"
path = "src/client/main.rs"

[lib]
name = "auto_desk"
path = "workspaces/qtile-ctl/src/qtile/lib.rs"

[workspace]
members = [
    "workspaces/bspwm",
    "workspaces/qtile",
    "workspaces/common",
    "workspaces/wm-lib",
    "workspaces/qtile-ctl"
]

[features]
default = ["common"]
bspwm = ["dep:bspwm"]
qtile = ["dep:qtile"]
common = ["systemctl", "media", "dep:common"]
systemctl = []
media = []

[dependencies]
clap = "3.2.8"
shellexpand = "2.1.0"
configparser = "3.0.0"
common = { path = "workspaces/common", optional=true}
qtile = { path = "workspaces/qtile", optional=true }
bspwm = { path = "workspaces/bspwm", optional=true }
qtile-ctl = { path = "workspaces/qtile-ctl", optional=true }
