# desktop-automater config file

[server]
listen_socket = "/tmp/desktop-automater"
wm_socket = "/tmp/QTILE_SOC"

[hooks]
listen = true
ignore_web = true
exec_ignore = [
			"firefox", 
			"brave", 
			"chromium",
			"chromium-browser",
			"kdeconnectd",
			"desktop-automat",
			"desktop-automater",
		 ]

[[hooks.hooks]]
event = "wifi-network-change"
hook = "~/.local/bin/network-notify"

[[hooks.hooks]]
event = "port-status-change"
hook = "~/.local/bin/port-switchboard.py"
