[package]
name = "config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shellexpand = "2.1"
configparser = "3.0.0"
toml = "0.5"
# serde_derive = "1.0.147"
serde = "1.0"