[package]
name = "auto-desk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.8"
shellexpand = "2.1.0"
configparser = "3.0.0"
